import { Router, Response, NextFunction } from 'express';
import { authenticateToken, requirePermission, AuthRequest, isCoacheeUser } from '../middleware/auth.middleware';
import { tenantResolver } from '../middleware/tenant.middleware';
import { CoachingEngagement } from '../models/CoachingEngagement.model';
import { CoachingSession } from '../models/CoachingSession.model';
import { SurveyTemplate } from '../models/SurveyTemplate.model';
import { SurveyResponse } from '../models/SurveyResponse.model';
import { User } from '../models/User.model';
import * as gcal from '../services/googleCalendar.service';
import {
  mirrorSessionToBooking,
  propagateSessionUpdate,
} from '../services/bookingCoachingSync.service';
import { cancelBooking } from '../services/booking.service';
import { BookingSettings } from '../models/BookingSettings.model';
import { buildPostSessionReflectionPrompt, callClaude } from '../services/ai.service';
import { sendEmail } from '../services/email.service';
import { notifyPostSessionForm, notifyPreSessionForm, createHubNotification, isNotificationEnabled } from '../services/hubNotification.service';
import { config } from '../config/env';

async function generateAndSendPostSessionForm(
  session: InstanceType<typeof CoachingSession>,
  organizationId: string,
  coachUserId: string,
  language: string = 'en',
): Promise<void> {
  const coachee = await User.findById(session.coacheeId).select('firstName lastName email');
  if (!coachee?.email) return;

  const prompt = buildPostSessionReflectionPrompt({
    coacheeName: coachee.firstName,
    topics: session.topics,
    sharedNotes: session.sharedNotes || undefined,
    coachNotes: session.coachNotes || undefined,
    growFocus: session.growFocus,
  }, language);

  const aiResponse = await callClaude(prompt, undefined, undefined, organizationId);
  let questions: Array<{ id: string; text: string; type: string; category: string }>;
  try {
    let clean = aiResponse.replace(/```(?:json)?\r?\n?/g, '').replace(/```/g, '').trim();
    const arrStart = clean.indexOf('[');
    const arrEnd = clean.lastIndexOf(']');
    if (arrStart !== -1 && arrEnd > arrStart) clean = clean.slice(arrStart, arrEnd + 1);
    questions = JSON.parse(clean);
  } catch {
    console.warn('[PostSession] AI returned unparseable questions');
    return;
  }

  const sessionDate = session.date.toLocaleDateString(language, {
    day: 'numeric', month: 'short', year: 'numeric',
  });

  const template = await SurveyTemplate.create({
    organizationId,
    moduleType: 'coaching',
    intakeType: 'assessment',
    title: `Post-Session Reflection — ${sessionDate}`,
    description: `Reflection questions for your coaching session on ${sessionDate}.`,
    instructions: 'Take a few minutes to reflect on your recent coaching session. There are no right or wrong answers.',
    isActive: true,
    isGlobal: false,
    isAutoGenerated: true,
    generatedForSessionId: session._id,
    createdBy: coachUserId,
    questions: questions.map((q) => ({
      id: q.id, text: q.text, type: 'text', category: q.category,
    })),
  });

  session.postSessionIntakeTemplateId = template._id as any;
  session.postSessionIntakeSentAt = new Date();
  await session.save();

  const coach = await User.findById(session.coachId).select('firstName lastName');
  const coachName = coach ? `${coach.firstName} ${coach.lastName}` : 'your coach';
  const intakeUrl = `${config.frontendUrl}/intake/${template._id}?sessionId=${session._id}`;

  await sendEmail({
    to: coachee.email,
    subject: `Post-session reflection — ${sessionDate}`,
    html: buildPostSessionEmailHtml({
      coacheeName: coachee.firstName,
      coachName,
      sessionDate,
      intakeUrl,
    }),
  });

  notifyPostSessionForm({
    coacheeId: session.coacheeId,
    organizationId: session.organizationId as any,
    coachName,
    sessionDate,
    intakeUrl,
  }).catch((err) => console.error('[PostSession] Hub notification failed:', err));

  console.log(`[PostSession] Sent reflection to ${coachee.email} for session ${session._id}`);
}

function buildPostSessionEmailHtml(p: {
  coacheeName: string;
  coachName: string;
  sessionDate: string;
  intakeUrl: string;
}): string {
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"/></head>
<body style="margin:0;padding:0;background:#EBF5FB;font-family:'Segoe UI',Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#EBF5FB;padding:40px 0;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0"
       style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.08);">
  <tr><td style="background:#1B2A47;padding:28px 36px;text-align:left;">
    <span style="color:#ffffff;font-size:20px;font-weight:700;letter-spacing:-0.3px;">ARTES</span>
  </td></tr>
  <tr><td style="padding:36px 36px 28px;">
    <h2 style="margin:0 0 16px;color:#1B2A47;font-size:20px;">
      Hi ${p.coacheeName}, time to reflect
    </h2>
    <p style="color:#5a6a7e;font-size:15px;line-height:1.6;margin:0 0 16px;">
      ${p.coachName} has prepared a short reflection for you following your
      coaching session on <strong>${p.sessionDate}</strong>.
    </p>
    <p style="color:#5a6a7e;font-size:14px;line-height:1.6;margin:0 0 24px;">
      Taking a few minutes to capture your thoughts while the session is fresh
      helps solidify your insights and keeps your growth on track.
    </p>
    <a href="${p.intakeUrl}"
       style="display:inline-block;background:#27C4A0;color:#ffffff;
              font-size:15px;font-weight:600;padding:12px 28px;
              border-radius:8px;text-decoration:none;">
      Complete Post-Session Reflection
    </a>
  </td></tr>
  <tr><td style="background:#f7f9fc;padding:20px 36px;border-top:1px solid #e8eef4;text-align:center;">
    <p style="margin:0;color:#9aa5b4;font-size:12px;line-height:1.5;">
      &copy; ${new Date().getFullYear()} HeadSoft Tech &times; Helena Coaching.
    </p>
  </td></tr>
</table>
</td></tr></table>
</body></html>`;
}

const router = Router();
router.use(authenticateToken, tenantResolver);

/** Resolve coachee name + email for calendar event details. */
async function resolveCoachee(coacheeId: string): Promise<{ name: string; email?: string }> {
  const coachee = await User.findById(coacheeId).select('firstName lastName email');
  return coachee
    ? { name: `${coachee.firstName} ${coachee.lastName}`, email: coachee.email }
    : { name: 'Unknown' };
}

/** Check if a coach has Google Calendar connected. */
async function isCalendarConnected(coachId: string): Promise<boolean> {
  const coach = await User.findById(coachId).select('googleCalendar.connected');
  return coach?.googleCalendar?.connected === true;
}

/** Validate that a pre-session intake template reference is legal for this org.
 *  Must be an active assessment-type template, either global or in the org. */
async function assertValidPreSessionIntake(
  templateId: unknown,
  organizationId: string,
): Promise<void> {
  if (!templateId) return;
  const tpl = await SurveyTemplate.findById(templateId as string)
    .setOptions({ bypassTenantCheck: true });
  if (!tpl) {
    throw Object.assign(new Error('Pre-session intake template not found'), { statusCode: 400 });
  }
  const sameOrg = tpl.organizationId?.toString() === organizationId;
  if (!tpl.isGlobal && !sameOrg) {
    throw Object.assign(new Error('Pre-session intake template not accessible'), { statusCode: 400 });
  }
  if (!tpl.isActive) {
    throw Object.assign(new Error('Pre-session intake template is inactive'), { statusCode: 400 });
  }
  if (tpl.intakeType !== 'assessment') {
    throw Object.assign(
      new Error('Pre-session intake must be an assessment-type template'),
      { statusCode: 400 },
    );
  }
}

/** Same rules as the pre-session validator. Kept as a separate function for
 *  clear error messages and future divergence. */
async function assertValidPostSessionIntake(
  templateId: unknown,
  organizationId: string,
): Promise<void> {
  if (!templateId) return;
  const tpl = await SurveyTemplate.findById(templateId as string)
    .setOptions({ bypassTenantCheck: true });
  if (!tpl) {
    throw Object.assign(new Error('Post-session intake template not found'), { statusCode: 400 });
  }
  const sameOrg = tpl.organizationId?.toString() === organizationId;
  if (!tpl.isGlobal && !sameOrg) {
    throw Object.assign(new Error('Post-session intake template not accessible'), { statusCode: 400 });
  }
  if (!tpl.isActive) {
    throw Object.assign(new Error('Post-session intake template is inactive'), { statusCode: 400 });
  }
  if (tpl.intakeType !== 'assessment') {
    throw Object.assign(
      new Error('Post-session intake must be an assessment-type template'),
      { statusCode: 400 },
    );
  }
}

/** Send a coach-assigned post-session form to the coachee (email + hub).
 *  Sets postSessionIntakeSentAt; does NOT create a new template. */
async function dispatchAssignedPostSessionForm(
  session: InstanceType<typeof CoachingSession>,
  language: string = 'en',
): Promise<void> {
  if (!session.postSessionIntakeTemplateId) return;
  const [coachee, coach, template] = await Promise.all([
    User.findById(session.coacheeId).select('firstName lastName email preferredLanguage'),
    User.findById(session.coachId).select('firstName lastName'),
    SurveyTemplate.findById(session.postSessionIntakeTemplateId).select('title'),
  ]);
  if (!coachee?.email || !coach || !template) return;

  const lang = coachee.preferredLanguage || language || 'en';
  const sessionDate = session.date.toLocaleDateString(lang, {
    day: 'numeric', month: 'short', year: 'numeric',
  });
  const coachName = `${coach.firstName} ${coach.lastName}`;
  const intakeUrl = `${config.frontendUrl}/intake/${template._id}?sessionId=${session._id}`;

  await sendEmail({
    to: coachee.email,
    subject: `Post-session reflection — ${sessionDate}`,
    html: buildPostSessionEmailHtml({
      coacheeName: coachee.firstName,
      coachName,
      sessionDate,
      intakeUrl,
    }),
  }).catch((err) => console.error('[PostSession] Email failed:', err));

  await notifyPostSessionForm({
    coacheeId: session.coacheeId,
    organizationId: session.organizationId as any,
    coachName,
    sessionDate,
    intakeUrl,
  }).catch((err) => console.error('[PostSession] Hub notification failed:', err));

  session.postSessionIntakeSentAt = new Date();
  await session.save();
}

/** Fields that become read-only once a session is `completed`. Editing any of
 *  these on a completed session must reject — coaches finalise the journal at
 *  completion time. */
const SESSION_LOCKED_FIELDS: ReadonlyArray<keyof InstanceType<typeof CoachingSession>> = [
  'coachNotes', 'sharedNotes', 'topics', 'growFocus', 'frameworks',
  'preSessionIntakeTemplateId', 'postSessionIntakeTemplateId',
  'preSessionRating', 'postSessionRating',
];

// ═══════════════════════════════════════════════════════════════════════════
// ENGAGEMENTS
// ═══════════════════════════════════════════════════════════════════════════

/** Per-role scoping for coaching reads.
 *  - admin / hr_manager: see every engagement/session in the org
 *  - coach:              see only engagements/sessions they own (coachId = self)
 *  - coachee:            see only engagements/sessions where they are the coachee
 */
function scopeCoachingFilter(req: AuthRequest, base: Record<string, unknown> = {}): Record<string, unknown> {
  const filter: Record<string, unknown> = { ...base, organizationId: req.user!.organizationId };
  if (req.user!.role === 'coach') filter['coachId'] = req.user!.userId;
  else if (isCoacheeUser(req)) filter['coacheeId'] = req.user!.userId;
  return filter;
}

/** List engagements — scoped per role. */
router.get('/engagements', async (req: AuthRequest, res: Response, next: NextFunction) => {
  try {
    const filter = scopeCoachingFilter(req);
    const engagements = await CoachingEngagement.find(filter)
      .populate('coacheeId', 'firstName lastName email department profilePicture')
      .populate('coachId', 'firstName lastName email profilePicture publicSlug')
      .populate('sponsorId', 'name email organization')
      .sort({ createdAt: -1 });
    console.info(
      `[Coaching] /engagements role=${req.user!.role} userId=${req.user!.userId} ` +
      `filter=${JSON.stringify(filter)} returned=${engagements.length}`,
    );
    res.json(engagements);
  } catch (e) { next(e); }
});

/** Get single engagement (scoped per role). */
router.get('/engagements/:id', async (req: AuthRequest, res: Response, next: NextFunction) => {
  try {
    const engagement = await CoachingEngagement.findOne(
      scopeCoachingFilter(req, { _id: req.params['id'] }),
    )
      .populate('coacheeId', 'firstName lastName email department profilePicture')
      .populate('coachId', 'firstName lastName email profilePicture')
      .populate('sponsorId', 'name email organization');
    if (!engagement) { res.status(404).json({ error: req.t('errors.engagementNotFound') }); return; }

    const coachSettings = await BookingSettings.findOne({ coachId: engagement.coachId })
      .select('rescheduleDeadlineHours')
      .setOptions({ bypassTenantCheck: true });
    const result = {
      ...engagement.toObject(),
      rescheduleDeadlineHours: coachSettings?.rescheduleDeadlineHours ?? 24,
    };
    res.json(result);
  } catch (e) { next(e); }
});

/** Create engagement. */
router.post(
  '/engagements',
  requirePermission('MANAGE_COACHING'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const engagement = await CoachingEngagement.create({
        ...req.body,
        organizationId: req.user!.organizationId,
        coachId: req.body.coachId || req.user!.userId,
      });
      const populated = await engagement.populate([
        { path: 'coacheeId', select: 'firstName lastName email department profilePicture' },
        { path: 'coachId', select: 'firstName lastName' },
      ]);

      // Notify coachee about the new engagement
      try {
        const coachee = await User.findById(engagement.coacheeId).select('firstName email');
        const coach = await User.findById(engagement.coachId).select('firstName lastName');
        if (coachee && coach && await isNotificationEnabled(engagement.coacheeId, 'engagementCreated')) {
          const coachName = `${coach.firstName} ${coach.lastName}`;

          sendEmail({
            to: coachee.email,
            subject: 'New coaching engagement started',
            html: `
              <h2 style="color:#1B2A47;margin:0 0 12px;font-size:22px;">New Coaching Engagement</h2>
              <p style="color:#5a6a7e;margin:0 0 16px;line-height:1.6;">
                Hi ${coachee.firstName}, <strong>${coachName}</strong> has started a coaching engagement with you.
              </p>
              <p style="color:#5a6a7e;margin:0 0 24px;line-height:1.6;">
                You can view your sessions, goals, and progress in ARTES.
              </p>
              <a href="${config.frontendUrl}/coaching" style="display:inline-block;background:#3A9FD6;color:#ffffff;padding:14px 28px;border-radius:6px;text-decoration:none;font-weight:600;font-size:15px;">View in ARTES</a>`,
          }).catch(err => console.error('[Coaching] Failed to send engagement email:', err));

          createHubNotification({
            userId: engagement.coacheeId,
            organizationId: engagement.organizationId,
            type: 'system',
            title: 'New Coaching Engagement',
            body: `${coachName} started a coaching engagement with you.`,
            link: '/coaching',
            category: 'engagementCreated',
          }).catch(err => console.error('[Coaching] Hub notification failed:', err));
        }
      } catch (notifyErr) {
        console.error('[Coaching] Notification failed:', notifyErr);
      }

      res.status(201).json(populated);
    } catch (e) { next(e); }
  }
);

/** Update engagement. */
router.put(
  '/engagements/:id',
  requirePermission('MANAGE_COACHING'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      // Reactivation: alumni/completed -> contracted/active. Stamp
      // reactivatedAt and clear pending alumni reminders so the cron
      // doesn't re-fire on the resumed engagement.
      const existing = await CoachingEngagement.findOne({
        _id: req.params['id'],
        organizationId: req.user!.organizationId,
      });
      if (!existing) { res.status(404).json({ error: req.t('errors.engagementNotFound') }); return; }

      const wasFinal = existing.status === 'alumni' || existing.status === 'completed';
      const becomingActive = ['contracted', 'active'].includes(req.body?.status);
      const isReactivation = wasFinal && becomingActive;

      Object.assign(existing, req.body);
      if (isReactivation) {
        existing.reactivatedAt = new Date();
        existing.completedAt = undefined;
        existing.alumniReminders = { disabled: false };
      }
      await existing.save();

      const engagement = await CoachingEngagement.findById(existing._id)
        .populate('coacheeId', 'firstName lastName email department profilePicture')
        .populate('coachId', 'firstName lastName email profilePicture')
        .populate('sponsorId', 'name email organization');
      res.json(engagement);
    } catch (e) { next(e); }
  }
);

/** Delete engagement (admin/hr_manager any; coach only their own). */
router.delete(
  '/engagements/:id',
  requirePermission('MANAGE_COACHING'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const filter: Record<string, unknown> = {
        _id: req.params['id'],
        organizationId: req.user!.organizationId,
      };
      // Coaches can only delete engagements they own.
      if (req.user!.role === 'coach') filter['coachId'] = req.user!.userId;

      const engagement = await CoachingEngagement.findOneAndDelete(filter);
      if (!engagement) { res.status(404).json({ error: req.t('errors.engagementNotFound') }); return; }

      // Cascade: delete every session under this engagement and cancel the
      // paired Booking + GCal event for each one. cancelBooking handles
      // GCal delete + email + cache invalidation for booking-paired
      // sessions; standalone sessions get a direct GCal delete fallback.
      const sessions = await CoachingSession.find({
        engagementId: req.params['id'],
        organizationId: req.user!.organizationId,
      });
      for (const session of sessions) {
        if (session.bookingId) {
          await cancelBooking(session.bookingId.toString(), 'coach', 'Engagement deleted')
            .catch((err) => console.error('[BookingSync] cascade cancelBooking failed:', err));
        } else if (session.googleEventId) {
          if (await isCalendarConnected(session.coachId.toString())) {
            await gcal.deleteCalendarEvent(session.coachId.toString(), session.googleEventId)
              .catch((calErr) => console.warn('[GCal] cascade delete failed:', calErr));
          }
        }
      }
      await CoachingSession.deleteMany({
        engagementId: req.params['id'],
        organizationId: req.user!.organizationId,
      });

      res.json({ message: 'Engagement and sessions deleted' });
    } catch (e) { next(e); }
  }
);

// ═══════════════════════════════════════════════════════════════════════════
// SESSIONS
// ═══════════════════════════════════════════════════════════════════════════

/** List sessions — scoped per role. Coachees see shared notes only. */
router.get('/sessions', async (req: AuthRequest, res: Response, next: NextFunction) => {
  try {
    const base: Record<string, unknown> = {};
    if (req.query['engagementId']) base['engagementId'] = req.query['engagementId'];
    const filter = scopeCoachingFilter(req, base);

    const selectFields = isCoacheeUser(req)
      ? '-coachNotes'   // NEVER expose private coach notes to coachees
      : undefined;

    const sessions = await CoachingSession.find(filter)
      .select(selectFields as string)
      .populate('coacheeId', 'firstName lastName profilePicture')
      .populate('coachId', 'firstName lastName email profilePicture')
      .populate('preSessionIntakeTemplateId', 'title moduleType intakeType')
      .sort({ date: -1 });

    // Annotate each session with whether the coachee has submitted the
    // pre-session intake, so coach + coachee UIs can show the right status.
    const preIds = sessions.filter((s) => s.preSessionIntakeTemplateId).map((s) => s._id);
    const postIds = sessions.filter((s) => s.postSessionIntakeTemplateId).map((s) => s._id);
    const allIds = [...new Set([...preIds, ...postIds].map(String))];
    const intakeResponses = allIds.length
      ? (await SurveyResponse.find({
          sessionId: { $in: allIds },
          organizationId: req.user!.organizationId,
        }).select('sessionId templateId').lean())
      : [];

    const preCompletedIds = new Set(
      intakeResponses
        .filter((r) => preIds.some((id) => String(id) === String(r.sessionId)))
        .map((r) => r.sessionId?.toString()),
    );
    const postCompletedIds = new Set(
      intakeResponses
        .filter((r) => postIds.some((id) => String(id) === String(r.sessionId))
          && sessions.find((s) => String(s._id) === String(r.sessionId))
              ?.postSessionIntakeTemplateId?.toString() === r.templateId?.toString())
        .map((r) => r.sessionId?.toString()),
    );

    const result = sessions.map((s) => ({
      ...s.toObject(),
      preSessionIntakeCompleted: preCompletedIds.has((s._id as { toString(): string }).toString()),
      postSessionIntakeCompleted: postCompletedIds.has((s._id as { toString(): string }).toString()),
    }));
    res.json(result);
  } catch (e) { next(e); }
});

/** Get single session (scoped per role). */
router.get('/sessions/:id', async (req: AuthRequest, res: Response, next: NextFunction) => {
  try {
    const selectFields = isCoacheeUser(req) ? '-coachNotes' : undefined;
    const session = await CoachingSession.findOne(
      scopeCoachingFilter(req, { _id: req.params['id'] }),
    )
      .select(selectFields as string)
      .populate('coacheeId', 'firstName lastName profilePicture')
      .populate('coachId', 'firstName lastName email profilePicture')
      .populate('preSessionIntakeTemplateId', 'title moduleType intakeType questions description instructions');
    if (!session) { res.status(404).json({ error: req.t('errors.sessionNotFound') }); return; }

    // Attach the coachee's pre-session intake response (if any) so the coach
    // sees completion status and the coachee sees "already submitted".
    let preSessionIntakeResponse = null;
    if (session.preSessionIntakeTemplateId) {
      preSessionIntakeResponse = await SurveyResponse.findOne({
        sessionId: session._id,
        organizationId: req.user!.organizationId,
      }).lean();
    }
    res.json({ ...session.toObject(), preSessionIntakeResponse });
  } catch (e) { next(e); }
});

/** Create session. */
router.post(
  '/sessions',
  requirePermission('MANAGE_COACHING'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      await assertValidPreSessionIntake(
        req.body.preSessionIntakeTemplateId,
        req.user!.organizationId,
      );
      const session = await CoachingSession.create({
        ...req.body,
        organizationId: req.user!.organizationId,
        coachId: req.body.coachId || req.user!.userId,
      });

      // Increment sessionsUsed on the engagement if session is completed.
      // Chemistry calls are complimentary and never consume the quota.
      if (session.status === 'completed' && !session.isChemistryCall) {
        await CoachingEngagement.findByIdAndUpdate(session.engagementId, { $inc: { sessionsUsed: 1 } });
      }

      // Google Calendar sync (creates Google Meet link)
      try {
        if (await isCalendarConnected(session.coachId.toString())) {
          const coachee = await resolveCoachee(session.coacheeId.toString());
          const { eventId, meetLink } = await gcal.createCalendarEvent(session.coachId.toString(), {
            date: session.date,
            duration: session.duration,
            coacheeName: coachee.name,
            coacheeEmail: coachee.email,
            sharedNotes: session.sharedNotes,
          });
          session.googleEventId = eventId;
          if (meetLink) session.googleMeetLink = meetLink;
          await session.save();
        }
      } catch (calErr) {
        console.warn('[GCal] Failed to create event:', calErr);
      }

      // Mirror this coach-created session into a Booking row so it shows
      // in booking dashboards and webhook sync covers it. Best-effort —
      // a failure here must not fail the session create.
      await mirrorSessionToBooking(session).catch((err) =>
        console.error('[BookingSync] Failed to mirror session to booking:', err),
      );

      const populated = await session.populate([
        { path: 'coacheeId', select: 'firstName lastName profilePicture' },
        { path: 'coachId', select: 'firstName lastName' },
      ]);

      // Notify coachee about the new session
      try {
        const coachee = await User.findById(session.coacheeId).select('firstName email');
        const coach = await User.findById(session.coachId).select('firstName lastName');
        if (coachee && coach && await isNotificationEnabled(session.coacheeId, 'sessionScheduled')) {
          const coachName = `${coach.firstName} ${coach.lastName}`;
          const sessionDate = session.date.toLocaleDateString(req.language || 'en', {
            weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
          });
          const sessionTime = session.date.toLocaleTimeString(req.language || 'en', { hour: '2-digit', minute: '2-digit' });

          sendEmail({
            to: coachee.email,
            subject: `New coaching session scheduled — ${sessionDate}`,
            html: `
              <h2 style="color:#1B2A47;margin:0 0 12px;font-size:22px;">New Session Scheduled</h2>
              <p style="color:#5a6a7e;margin:0 0 16px;line-height:1.6;">
                Hi ${coachee.firstName}, <strong>${coachName}</strong> has scheduled a coaching session with you.
              </p>
              <div style="background:#f0f9f4;border-left:4px solid #27C4A0;padding:14px 18px;border-radius:0 8px 8px 0;margin:0 0 20px;">
                <p style="margin:0 0 4px;color:#1B2A47;font-weight:600;">${sessionDate}</p>
                <p style="margin:0;color:#5a6a7e;">${sessionTime} &middot; ${session.duration} minutes</p>
              </div>
              ${session.googleMeetLink ? `<a href="${session.googleMeetLink}" style="display:inline-block;background:#3A9FD6;color:#ffffff;padding:14px 28px;border-radius:6px;text-decoration:none;font-weight:600;font-size:15px;margin:0 8px 12px 0;">Join Google Meet</a>` : ''}
              <a href="${config.frontendUrl}/coaching" style="display:inline-block;background:#1B2A47;color:#ffffff;padding:14px 28px;border-radius:6px;text-decoration:none;font-weight:600;font-size:15px;">View in ARTES</a>`,
          }).catch(err => console.error('[Coaching] Failed to send session email:', err));

          createHubNotification({
            userId: session.coacheeId,
            organizationId: session.organizationId,
            type: 'system',
            title: 'New Session Scheduled',
            body: `${coachName} scheduled a session on ${sessionDate} at ${sessionTime}.`,
            link: '/coaching',
            category: 'sessionScheduled',
          }).catch(err => console.error('[Coaching] Hub notification failed:', err));
        }
      } catch (notifyErr) {
        console.error('[Coaching] Notification failed:', notifyErr);
      }

      res.status(201).json(populated);
    } catch (e) { next(e); }
  }
);

/** Update session (notes, status, ratings). */
router.put(
  '/sessions/:id',
  requirePermission('MANAGE_COACHING'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const existing = await CoachingSession.findOne({
        _id: req.params['id'],
        organizationId: req.user!.organizationId,
      });
      if (!existing) { res.status(404).json({ error: req.t('errors.sessionNotFound') }); return; }

      // Once a session is `completed`, the journal is locked. Block edits to
      // notes/templates/ratings, and block status changes (Mark Complete is a
      // one-way transition — re-pressing or re-cancelling is rejected).
      if (existing.status === 'completed') {
        const incomingStatus = req.body.status;
        if (incomingStatus !== undefined && incomingStatus !== 'completed') {
          res.status(409).json({ error: req.t('errors.sessionLockedCompleted') });
          return;
        }
        for (const field of SESSION_LOCKED_FIELDS) {
          if (!(field in req.body)) continue;
          const next = req.body[field];
          const cur = (existing as any)[field];
          const changed = Array.isArray(cur)
            ? JSON.stringify([...cur].sort()) !== JSON.stringify([...(next ?? [])].sort())
            : String(cur ?? '') !== String(next ?? '');
          if (changed) {
            res.status(409).json({ error: req.t('errors.sessionLockedCompleted') });
            return;
          }
        }
      }

      if (
        req.body.preSessionIntakeTemplateId
        && req.body.preSessionIntakeTemplateId !== existing.preSessionIntakeTemplateId?.toString()
      ) {
        await assertValidPreSessionIntake(
          req.body.preSessionIntakeTemplateId,
          req.user!.organizationId,
        );
      }
      if (
        req.body.postSessionIntakeTemplateId
        && req.body.postSessionIntakeTemplateId !== existing.postSessionIntakeTemplateId?.toString()
      ) {
        await assertValidPostSessionIntake(
          req.body.postSessionIntakeTemplateId,
          req.user!.organizationId,
        );
      }

      const preSessionTemplateChanged =
        req.body.preSessionIntakeTemplateId
        && req.body.preSessionIntakeTemplateId !== existing.preSessionIntakeTemplateId?.toString();

      const wasNotCompleted = existing.status !== 'completed';
      const prev = { date: existing.date, status: existing.status };
      Object.assign(existing, req.body);
      await existing.save();

      // Notify coachee when a pre-session assessment form is added/changed
      if (preSessionTemplateChanged) {
        (async () => {
          try {
            const [coachee, coach, template] = await Promise.all([
              User.findById(existing.coacheeId).select('firstName email preferredLanguage'),
              User.findById(existing.coachId).select('firstName lastName'),
              SurveyTemplate.findById(existing.preSessionIntakeTemplateId).select('title'),
            ]);
            if (!coachee?.email || !coach || !template) return;

            const coachName = `${coach.firstName} ${coach.lastName}`;
            const sessionDate = existing.date.toLocaleDateString(coachee.preferredLanguage || 'en', {
              weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
            });
            const intakeUrl = `${config.frontendUrl}/intake/${template._id}?sessionId=${existing._id}`;

            await sendEmail({
              to: coachee.email,
              subject: `Pre-session form ready — ${sessionDate}`,
              html: `<p>Hi ${coachee.firstName},</p>
                     <p>${coachName} has added a pre-session form for your session on <strong>${sessionDate}</strong>.</p>
                     <p><a href="${intakeUrl}">Complete Pre-Session Form: ${template.title}</a></p>`,
            });

            await notifyPreSessionForm({
              coacheeId: existing.coacheeId,
              organizationId: req.user!.organizationId,
              coachName,
              sessionDate,
              templateTitle: template.title,
              intakeUrl,
            });
          } catch (err) {
            console.error('[Coaching] Failed to notify coachee about pre-session form:', err);
          }
        })();
      }

      // Mirror date / status changes into the linked Booking
      await propagateSessionUpdate(existing, prev).catch((err) =>
        console.error('[BookingSync] Failed to propagate session update:', err),
      );

      // If status changed to completed, increment engagement counter and send
      // the post-session form. Coach-assigned template wins; otherwise we fall
      // back to AI auto-generation when context is available.
      // Chemistry calls are complimentary and skip the quota increment.
      if (wasNotCompleted && existing.status === 'completed') {
        if (!existing.isChemistryCall) {
          await CoachingEngagement.findByIdAndUpdate(existing.engagementId, { $inc: { sessionsUsed: 1 } });
        }

        if (existing.postSessionIntakeTemplateId && !existing.postSessionIntakeSentAt) {
          dispatchAssignedPostSessionForm(existing, req.language)
            .catch((err) => console.error('[PostSession] Assigned dispatch failed:', err));
        } else if (!existing.postSessionIntakeTemplateId) {
          const hasCtx = existing.topics.length > 0
            || (existing.sharedNotes ?? '').trim()
            || (existing.coachNotes ?? '').trim();
          if (hasCtx) {
            generateAndSendPostSessionForm(existing, req.user!.organizationId, req.user!.userId, req.language)
              .catch((err) => console.error('[PostSession] Auto-generate failed:', err));
          }
        }
      }

      // Google Calendar sync
      try {
        if (existing.googleEventId && await isCalendarConnected(existing.coachId.toString())) {
          const coachee = await resolveCoachee(existing.coacheeId.toString());
          await gcal.updateCalendarEvent(existing.coachId.toString(), existing.googleEventId, {
            date: existing.date,
            duration: existing.duration,
            coacheeName: coachee.name,
            coacheeEmail: coachee.email,
            sharedNotes: existing.sharedNotes,
            status: existing.status,
          });
        }
      } catch (calErr) {
        console.warn('[GCal] Failed to update event:', calErr);
      }

      await existing.populate([
        { path: 'coacheeId', select: 'firstName lastName profilePicture' },
        { path: 'coachId', select: 'firstName lastName' },
      ]);
      res.json(existing);
    } catch (e) { next(e); }
  }
);

/** Generate a post-session reflection form from session context, create a
 *  SurveyTemplate, link it to the session, and email the coachee. */
router.post(
  '/sessions/:id/post-session-form',
  requirePermission('MANAGE_COACHING'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const session = await CoachingSession.findOne({
        _id: req.params['id'],
        organizationId: req.user!.organizationId,
      });
      if (!session) { res.status(404).json({ error: req.t('errors.sessionNotFound') }); return; }

      if (session.postSessionIntakeTemplateId) {
        res.status(409).json({ error: req.t('errors.postSessionFormAlreadyGenerated') });
        return;
      }

      const coachee = await User.findById(session.coacheeId).select('firstName lastName email');
      if (!coachee?.email) {
        res.status(400).json({ error: req.t('errors.coacheeNotFoundOrNoEmail') });
        return;
      }

      const summary = typeof req.body.summary === 'string' ? req.body.summary.trim() : '';
      const hasContext = session.topics.length > 0
        || (session.sharedNotes ?? '').trim()
        || (session.coachNotes ?? '').trim()
        || summary;

      if (!hasContext) {
        res.status(400).json({
          error: req.t('errors.noSessionContext'),
        });
        return;
      }

      const prompt = buildPostSessionReflectionPrompt({
        coacheeName: coachee.firstName,
        topics: session.topics,
        sharedNotes: session.sharedNotes || undefined,
        coachNotes: session.coachNotes || undefined,
        summary: summary || undefined,
        growFocus: session.growFocus,
      }, req.language);

      const aiResponse = await callClaude(prompt, undefined, undefined, req.user!.organizationId);

      let questions: Array<{ id: string; text: string; type: string; category: string }>;
      try {
        let clean = aiResponse.replace(/```(?:json)?\r?\n?/g, '').replace(/```/g, '').trim();
        const arrStart = clean.indexOf('[');
        const arrEnd = clean.lastIndexOf(']');
        if (arrStart !== -1 && arrEnd > arrStart) clean = clean.slice(arrStart, arrEnd + 1);
        questions = JSON.parse(clean);
      } catch {
        res.status(500).json({ error: req.t('errors.aiInvalidQuestionFormat') });
        return;
      }

      const sessionDate = session.date.toLocaleDateString(req.language || 'en', {
        day: 'numeric', month: 'short', year: 'numeric',
      });

      const template = await SurveyTemplate.create({
        organizationId: req.user!.organizationId,
        moduleType: 'coaching',
        intakeType: 'assessment',
        title: `Post-Session Reflection — ${sessionDate}`,
        description: `Reflection questions for your coaching session on ${sessionDate}.`,
        instructions: 'Take a few minutes to reflect on your recent coaching session. There are no right or wrong answers — your honest thoughts help both you and your coach.',
        isActive: true,
        isGlobal: false,
        isAutoGenerated: true,
        generatedForSessionId: session._id,
        createdBy: req.user!.userId,
        questions: questions.map((q) => ({
          id: q.id,
          text: q.text,
          type: 'text',
          category: q.category,
        })),
      });

      session.postSessionIntakeTemplateId = template._id as any;
      session.postSessionIntakeSentAt = new Date();
      await session.save();

      const intakeUrl = `${config.frontendUrl}/intake/${template._id}?sessionId=${session._id}`;
      const coach = await User.findById(session.coachId).select('firstName lastName');
      const coachName = coach ? `${coach.firstName} ${coach.lastName}` : 'your coach';

      await sendEmail({
        to: coachee.email,
        subject: `Post-session reflection — ${sessionDate}`,
        html: buildPostSessionEmailHtml({
          coacheeName: coachee.firstName,
          coachName,
          sessionDate,
          intakeUrl,
        }),
      });

      res.status(201).json({
        templateId: template._id,
        questionCount: questions.length,
        sentTo: coachee.email,
      });
    } catch (e) { next(e); }
  }
);

/** Delete session. */
router.delete(
  '/sessions/:id',
  requirePermission('MANAGE_COACHING'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const session = await CoachingSession.findOneAndDelete({
        _id: req.params['id'],
        organizationId: req.user!.organizationId,
      });
      if (!session) { res.status(404).json({ error: req.t('errors.sessionNotFound') }); return; }

      // If the session has a paired Booking, cancel through cancelBooking()
      // so GCal delete + cancellation email + cache invalidation all run.
      // For sessions without a paired Booking (manually created, no public
      // flow), fall back to deleting the GCal event directly.
      if (session.bookingId) {
        try {
          await cancelBooking(session.bookingId.toString(), 'coach', 'Session deleted');
        } catch (err) {
          console.error('[BookingSync] cancelBooking on session delete failed:', err);
          // Best-effort fallback: at least attempt the GCal delete.
          if (session.googleEventId && await isCalendarConnected(session.coachId.toString())) {
            await gcal.deleteCalendarEvent(session.coachId.toString(), session.googleEventId)
              .catch((calErr) => console.warn('[GCal] fallback delete failed:', calErr));
          }
        }
      } else {
        try {
          if (session.googleEventId && await isCalendarConnected(session.coachId.toString())) {
            await gcal.deleteCalendarEvent(session.coachId.toString(), session.googleEventId);
          }
        } catch (calErr) {
          console.warn('[GCal] Failed to delete event:', calErr);
        }
      }

      res.json({ message: 'Session deleted' });
    } catch (e) { next(e); }
  }
);

// ═══════════════════════════════════════════════════════════════════════════
// DASHBOARD STATS
// ═══════════════════════════════════════════════════════════════════════════

router.get('/dashboard', async (req: AuthRequest, res: Response, next: NextFunction) => {
  try {
    const filter = scopeCoachingFilter(req);

    const [engagements, sessions] = await Promise.all([
      CoachingEngagement.find(filter).lean(),
      CoachingSession.find(filter).lean(),
    ]);

    const activeEngagements = engagements.filter((e) => e.status === 'active').length;
    const completedSessions = sessions.filter((s) => s.status === 'completed').length;
    const totalHours = sessions
      .filter((s) => s.status === 'completed')
      .reduce((sum, s) => sum + (s.duration || 60) / 60, 0);

    // Upcoming sessions (next 30 days)
    const now = new Date();
    const in30Days = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
    const upcoming = sessions.filter((s) =>
      s.status === 'scheduled' && new Date(s.date) >= now && new Date(s.date) <= in30Days
    ).length;

    res.json({
      activeEngagements,
      totalEngagements: engagements.length,
      completedSessions,
      totalHours: Math.round(totalHours * 10) / 10,
      upcomingSessions: upcoming,
      byStatus: {
        prospect: engagements.filter((e) => e.status === 'prospect').length,
        contracted: engagements.filter((e) => e.status === 'contracted').length,
        active: activeEngagements,
        paused: engagements.filter((e) => e.status === 'paused').length,
        completed: engagements.filter((e) => e.status === 'completed').length,
        alumni: engagements.filter((e) => e.status === 'alumni').length,
      },
    });
  } catch (e) { next(e); }
});

// ═══════════════════════════════════════════════════════════════════════════
// COACHEE BILLING
// ═══════════════════════════════════════════════════════════════════════════

/** Billing summary for a coachee across all rebillable engagements. */
router.get(
  '/billing/coachee/:coacheeId',
  requirePermission('MANAGE_COACHING'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const orgId = req.user!.organizationId;
      const coacheeId = req.params['coacheeId'];

      const billingFilter: Record<string, unknown> = {
        organizationId: orgId,
        coacheeId,
        billingMode: 'sponsor',
      };
      // Coaches can only see billing for engagements they own.
      if (req.user!.role === 'coach') billingFilter['coachId'] = req.user!.userId;

      const engagements = await CoachingEngagement.find(billingFilter)
        .populate('coachId', 'firstName lastName email profilePicture')
      .populate('sponsorId', 'name email organization')
        .lean();

      const engagementIds = engagements.map((e) => e._id);

      const sessions = await CoachingSession.find({
        organizationId: orgId,
        engagementId: { $in: engagementIds },
      })
        .select('-coachNotes')
        .sort({ date: -1 })
        .lean();

      // Build per-engagement billing summary
      // Billing is based on the full engagement (sessionsPurchased), not just completed sessions.
      const items = engagements.map((eng) => {
        const engSessions = sessions.filter(
          (s) => s.engagementId.toString() === eng._id.toString()
        );
        const completed = engSessions.filter((s) => s.status === 'completed');
        const rate = eng.hourlyRate ?? 0;
        const billedHours = eng.sessionsPurchased ?? 0;
        const totalAmount = billedHours * rate;
        const completedHours = completed.reduce((sum, s) => sum + (s.duration || 60), 0) / 60;

        return {
          engagementId: eng._id,
          coach: eng.coachId,
          status: eng.status,
          hourlyRate: rate,
          sessionsPurchased: eng.sessionsPurchased,
          sessionsUsed: eng.sessionsUsed,
          sessionsCompleted: completed.length,
          sessionsTotal: engSessions.length,
          billedHours,
          completedHours: Math.round(completedHours * 100) / 100,
          totalAmount: Math.round(totalAmount * 100) / 100,
          sessions: engSessions.map((s) => ({
            _id: s._id,
            date: s.date,
            duration: s.duration,
            status: s.status,
            format: s.format,
          })),
        };
      });

      const grandTotal = items.reduce((sum, i) => sum + i.totalAmount, 0);
      const grandHours = items.reduce((sum, i) => sum + i.billedHours, 0);

      // Get coachee info
      const coachee = await User.findById(coacheeId).select('firstName lastName email department profilePicture');

      res.json({
        coachee,
        engagements: items,
        summary: {
          totalEngagements: items.length,
          totalHours: Math.round(grandHours * 100) / 100,
          totalAmount: Math.round(grandTotal * 100) / 100,
        },
      });
    } catch (e) { next(e); }
  }
);

export default router;
