import { Router, Response, NextFunction } from 'express';
import { createHash } from 'crypto';
import { authenticateToken, requirePermission, AuthRequest } from '../middleware/auth.middleware';
import { tenantResolver } from '../middleware/tenant.middleware';
import { SurveyTemplate } from '../models/SurveyTemplate.model';
import { SurveyResponse } from '../models/SurveyResponse.model';
import { CoachingSession } from '../models/CoachingSession.model';
import { callClaude } from '../services/ai.service';

function makeSubmissionToken(userId: string, templateId: string, sessionId?: string): string {
  const payload = sessionId ? `${userId}:${templateId}:${sessionId}` : `${userId}:${templateId}`;
  return createHash('sha256').update(payload).digest('hex');
}

const TWENTY_FOUR_HOURS_MS = 24 * 60 * 60 * 1000;

async function isSessionIntakeAccessible(sessionId: string): Promise<{ ok: boolean; reason?: string }> {
  const session = await CoachingSession.findById(sessionId)
    .select('date preSessionIntakeSentAt status')
    .setOptions({ bypassTenantCheck: true });
  if (!session) return { ok: false, reason: 'Session not found.' };
  if (session.status !== 'scheduled') return { ok: false, reason: 'Session is no longer scheduled.' };
  const hoursUntil = (session.date.getTime() - Date.now()) / (60 * 60 * 1000);
  if (session.preSessionIntakeSentAt) return { ok: true };
  if (hoursUntil <= 24) return { ok: true };
  return { ok: false, reason: 'This form will be available 24 hours before your session.' };
}

const router = Router();
const MIN_GROUP_SIZE = 5;

router.use(authenticateToken, tenantResolver);

router.post(
  '/templates',
  requirePermission('MANAGE_INTAKE_TEMPLATES'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const template = await SurveyTemplate.create({
        ...req.body,
        organizationId: req.user!.organizationId,
        createdBy: req.user!.userId,
      });
      res.status(201).json(template);
    } catch (e) {
      next(e);
    }
  }
);

router.get('/', async (req: AuthRequest, res: Response, next: NextFunction) => {
  try {
    const templates = await SurveyTemplate.find({
      $or: [
        { organizationId: req.user!.organizationId },
        { isGlobal: true },
      ],
      isActive: true,
      sourceTemplateId: { $exists: false },
    }).setOptions({ bypassTenantCheck: true });
    res.json(templates);
  } catch (e) {
    next(e);
  }
});

router.get(
  '/templates',
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const filter: Record<string, unknown> = {
        $or: [
          { organizationId: req.user!.organizationId },
          { isGlobal: true },
        ],
      };
      if (req.query['includeInactive'] !== 'true') {
        filter['isActive'] = true;
      }
      filter['isAutoGenerated'] = { $ne: true };
      filter['sourceTemplateId'] = { $exists: false };
      const templates = await SurveyTemplate.find(filter).setOptions({ bypassTenantCheck: true });
      res.json(templates);
    } catch (e) {
      next(e);
    }
  }
);

router.get(
  '/templates/:id',
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const template = await SurveyTemplate.findOne({
        _id: req.params['id'],
        $or: [
          { organizationId: req.user!.organizationId },
          { isGlobal: true },
        ],
      }).setOptions({ bypassTenantCheck: true });
      if (!template) {
        res.status(404).json({ error: req.t('errors.intakeTemplateNotFound') });
        return;
      }
      if (!template.isActive) {
        res.status(410).json({ error: req.t('errors.intakeNoLongerActive') });
        return;
      }
      res.json(template);
    } catch (e) {
      next(e);
    }
  }
);

router.put(
  '/templates/:id',
  requirePermission('MANAGE_INTAKE_TEMPLATES'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const template = await SurveyTemplate.findOneAndUpdate(
        { _id: req.params['id'], $or: [{ organizationId: req.user!.organizationId }, { isGlobal: true }] },
        req.body,
        { new: true, runValidators: true }
      ).setOptions({ bypassTenantCheck: true });
      if (!template) {
        res.status(404).json({ error: req.t('errors.intakeTemplateNotFound') });
        return;
      }
      res.json(template);
    } catch (e) {
      next(e);
    }
  }
);

router.post(
  '/templates/:id/translate',
  requirePermission('MANAGE_INTAKE_TEMPLATES'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const { targetLanguage } = req.body;
      if (!targetLanguage || !['en', 'fr', 'es'].includes(targetLanguage)) {
        res.status(400).json({ error: 'Valid targetLanguage (en, fr, es) is required' });
        return;
      }

      const template = await SurveyTemplate.findOne({
        _id: req.params['id'],
        $or: [{ organizationId: req.user!.organizationId }, { isGlobal: true }],
      }).setOptions({ bypassTenantCheck: true });

      if (!template) {
        res.status(404).json({ error: req.t('errors.intakeTemplateNotFound') });
        return;
      }

      const langNames: Record<string, string> = {
        en: 'English',
        fr: 'French (use formal "vous" register)',
        es: 'Spanish (Latin American)',
      };

      const questionsForAI = template.questions.map((q) => ({
        id: q.id,
        text: q.text,
        type: q.type,
        category: q.category,
        options: q.options?.map((o) => ({ value: o.value, text: o.text, subscale: o.subscale })),
        scale_range: q.scale_range ? {
          min: q.scale_range.min,
          max: q.scale_range.max,
          labels: q.scale_range.labels instanceof Map
            ? Object.fromEntries(q.scale_range.labels)
            : q.scale_range.labels || undefined,
        } : undefined,
      }));

      const prompt = `Translate the following intake/survey content into ${langNames[targetLanguage]}.

TITLE: ${template.title}
DESCRIPTION: ${template.description || ''}
INSTRUCTIONS: ${template.instructions || ''}

QUESTIONS (JSON):
${JSON.stringify(questionsForAI, null, 2)}

Return ONLY valid JSON with this exact structure:
{
  "title": "translated title",
  "description": "translated description",
  "instructions": "translated instructions",
  "questions": [
    {
      "id": "keep original id unchanged",
      "text": "translated question text",
      "category": "translated category",
      "options": [{"value": "keep original", "text": "translated text", "subscale": "keep original"}],
      "scale_labels": {"1": "translated label", "5": "translated label"}
    }
  ]
}

Rules:
- Translate text, category, option text, scale labels, description, instructions, and title
- Keep id, value, subscale, type, and all numeric/structural fields unchanged
- Omit options/scale_labels if the original question doesn't have them
- Return ONLY the JSON object, no markdown fences`;

      const raw = await callClaude(prompt, undefined, 4096);
      const jsonStr = raw.slice(raw.indexOf('{'), raw.lastIndexOf('}') + 1);
      const translated = JSON.parse(jsonStr);

      const updatedQuestions = template.questions.map((q) => {
        const tq = translated.questions?.find((t: { id: string }) => t.id === q.id);
        if (!tq) return q;
        const updated: Record<string, unknown> = (q as any).toObject ? (q as any).toObject() : { ...q };
        updated.text = tq.text || q.text;
        if (tq.category) updated.category = tq.category;
        if (tq.options && updated.options) {
          updated.options = (updated.options as any[]).map((o: any) => {
            const to = tq.options?.find((opt: { value: string }) => opt.value === o.value);
            return to ? { ...o, text: to.text || o.text } : o;
          });
        }
        if (tq.scale_labels && updated.scale_range) {
          updated.scale_range = { ...(updated.scale_range as any), labels: tq.scale_labels };
        }
        return updated;
      });

      const sourceObj = template.toObject();
      delete (sourceObj as any)._id;
      delete (sourceObj as any).__v;
      delete (sourceObj as any).createdAt;
      delete (sourceObj as any).updatedAt;

      const sourceId = template.sourceTemplateId || template._id;

      const copy = await SurveyTemplate.create({
        ...sourceObj,
        title: translated.title || template.title,
        description: translated.description ?? template.description,
        instructions: translated.instructions ?? template.instructions,
        questions: updatedQuestions,
        language: targetLanguage,
        sourceTemplateId: sourceId,
        isGlobal: false,
        organizationId: req.user!.organizationId,
        createdBy: req.user!.userId,
      });

      res.status(201).json(copy);
    } catch (e) {
      next(e);
    }
  }
);

router.get(
  '/templates/:id/translations',
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const templateId = req.params['id'];
      const template = await SurveyTemplate.findById(templateId)
        .setOptions({ bypassTenantCheck: true });
      if (!template) {
        res.status(404).json({ error: req.t('errors.intakeTemplateNotFound') });
        return;
      }

      const sourceId = template.sourceTemplateId || template._id;

      const translations = await SurveyTemplate.find({
        $or: [
          { _id: sourceId },
          { sourceTemplateId: sourceId },
        ],
        _id: { $ne: templateId },
      })
        .select('_id title language')
        .setOptions({ bypassTenantCheck: true });

      res.json(translations);
    } catch (e) {
      next(e);
    }
  }
);

router.delete(
  '/templates/:id',
  requirePermission('MANAGE_INTAKE_TEMPLATES'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const template = await SurveyTemplate.findOneAndDelete({
        _id: req.params['id'],
        $or: [{ organizationId: req.user!.organizationId }, { isGlobal: true }],
      }).setOptions({ bypassTenantCheck: true });
      if (!template) {
        res.status(404).json({ error: req.t('errors.intakeTemplateNotFound') });
        return;
      }
      res.json({ message: 'Template deleted' });
    } catch (e) {
      next(e);
    }
  }
);

// Check if the authenticated user already submitted a response for this template
router.get('/check/:templateId', async (req: AuthRequest, res: Response, next: NextFunction) => {
  try {
    const sessionId = typeof req.query['sessionId'] === 'string' ? req.query['sessionId'] : undefined;

    if (sessionId) {
      const access = await isSessionIntakeAccessible(sessionId);
      if (!access.ok) {
        res.json({ alreadySubmitted: false, locked: true, lockedReason: access.reason });
        return;
      }
    }

    const token = makeSubmissionToken(
      req.user!.userId.toString(),
      req.params['templateId'],
      sessionId,
    );
    const existing = await SurveyResponse.findOne({ submissionToken: token }).setOptions({ bypassTenantCheck: true });
    res.json({ alreadySubmitted: !!existing, locked: false });
  } catch (e) {
    next(e);
  }
});

router.post('/respond', async (req: AuthRequest, res: Response, next: NextFunction) => {
  try {
    const {
      templateId, isAnonymous = true, departmentId, responses,
      coacheeId, sessionFormat, targetName, sessionId, respondentLanguage,
    } = req.body;

    // 24h gate: coachees can only submit session-bound intakes within 24h of the session.
    // Coaches submitting on behalf of a coachee bypass this check.
    if (sessionId && !coacheeId) {
      const access = await isSessionIntakeAccessible(sessionId);
      if (!access.ok) {
        res.status(403).json({ error: access.reason });
        return;
      }
    }

    const tokenSubject = coacheeId ? coacheeId.toString() : req.user!.userId.toString();
    const submissionToken = makeSubmissionToken(tokenSubject, templateId, sessionId);

    // Duplicate check — DB unique index is the safety net, but give a friendly error here
    const existing = await SurveyResponse.findOne({ submissionToken }).setOptions({ bypassTenantCheck: true });
    if (existing) {
      res.status(409).json({ error: req.t('errors.responseAlreadySubmitted') });
      return;
    }

    const doc: Record<string, unknown> = {
      organizationId: req.user!.organizationId,
      templateId,
      submissionToken,
      departmentId,
      respondentLanguage: respondentLanguage || req.language || 'en',
      responses,
      isAnonymous: coacheeId ? false : isAnonymous,
      submittedAt: new Date(),
    };

    if (sessionId) doc['sessionId'] = sessionId;

    // Coach-led submission: attribute to the coachee
    if (coacheeId) {
      doc['respondentId'] = coacheeId;
      doc['coachId'] = req.user!.userId;
      if (sessionFormat) doc['sessionFormat'] = sessionFormat;
      if (targetName)    doc['targetName']    = targetName;
    } else if (!isAnonymous) {
      doc['respondentId'] = req.user!.userId;
    }

    const response = await SurveyResponse.create(doc);
    res.status(201).json({ message: 'Response recorded', id: response._id });
  } catch (e) {
    next(e);
  }
});

router.get(
  '/responses/:templateId/count',
  requirePermission('VIEW_CONFLICT_RESPONSES'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const count = await SurveyResponse.countDocuments({
        organizationId: req.user!.organizationId,
        templateId: req.params['templateId'],
      });
      res.json({ count });
    } catch (e) {
      next(e);
    }
  }
);

router.delete(
  '/responses/:templateId',
  requirePermission('MANAGE_INTAKE_TEMPLATES'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const result = await SurveyResponse.deleteMany({
        organizationId: req.user!.organizationId,
        templateId: req.params['templateId'],
      });
      res.json({ message: 'Responses cleared', deletedCount: result.deletedCount });
    } catch (e) {
      next(e);
    }
  }
);

router.get(
  '/responses/:templateId',
  requirePermission('VIEW_CONFLICT_RESPONSES'),
  async (req: AuthRequest, res: Response, next: NextFunction) => {
    try {
      const organizationId = req.user!.organizationId;
      const templateId = req.params['templateId'];
      const sessionId = typeof req.query['sessionId'] === 'string' ? req.query['sessionId'] : undefined;

      const template = await SurveyTemplate.findById(templateId).setOptions({ bypassTenantCheck: true });
      const isSurvey = !template || template.intakeType === 'survey';
      // When scoped to a single session the aggregation floor doesn't apply —
      // there's exactly one known respondent and anonymity is not at stake.
      const minRequired = sessionId
        ? 1
        : template?.minResponsesForAnalysis ?? (isSurvey ? MIN_GROUP_SIZE : 1);

      const filter: Record<string, unknown> = { organizationId, templateId };
      if (sessionId) filter['sessionId'] = sessionId;

      const count = await SurveyResponse.countDocuments(filter);

      if (count < minRequired) {
        res.status(403).json({
          error: req.t('errors.minimumResponsesRequired', { min: minRequired, count }),
        });
        return;
      }

      // Return responses without respondentId to protect anonymity — except
      // when scoped to a single session, where the response is already
      // coachee-attributed by design.
      const query = SurveyResponse.find(filter);
      if (!sessionId) query.select('-respondentId');
      const responses = await query;

      res.json({ count, responses });
    } catch (e) {
      next(e);
    }
  }
);

export default router;
