import { Component, OnInit, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTableModule } from '@angular/material/table';
import { MatChipsModule } from '@angular/material/chips';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatMenuModule } from '@angular/material/menu';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { MatDividerModule } from '@angular/material/divider';
import { ApiService } from '../../../core/api.service';
import { SurveyTemplateDialogComponent } from '../survey-template-dialog/survey-template-dialog.component';
import { SurveyResponsesDialogComponent } from '../survey-responses-dialog/survey-responses-dialog.component';
import { IntakeAssignDialogComponent } from '../intake-assign-dialog/intake-assign-dialog.component';
import { ConfirmDialogComponent } from '../../../shared/confirm-dialog/confirm-dialog.component';
import { TranslateModule, TranslateService } from '@ngx-translate/core';

interface SurveyTemplate {
  _id: string;
  title: string;
  moduleType: 'conflict' | 'neuroinclusion' | 'succession' | 'coaching';
  intakeType: 'survey' | 'interview' | 'assessment';
  questions: { id: string; text: string; type: string; category: string }[];
  isActive: boolean;
  isAutoGenerated?: boolean;
  isGlobal?: boolean;
  instrumentId?: string;
  instrumentVersion?: string;
  description?: string;
  instructions?: string;
  level_of_analysis?: string;
  relationship_target?: string;
  single_construct?: boolean;
  rater_pool?: unknown;
  aggregation_method?: string;
  minimum_respondents_per_team?: number;
  scoring?: unknown;
  rater_type?: string;
  analysisPrompt?: string;
  language?: string;
  sourceTemplateId?: string;
  createdAt: string;
  responseCount?: number;
}

@Component({
  selector: 'app-survey-management',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatButtonModule,
    MatIconModule,
    MatTableModule,
    MatChipsModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatSnackBarModule,
    MatMenuModule,
    MatTooltipModule,
    MatSlideToggleModule,
    MatDividerModule,
    TranslateModule,
  ],
  template: `
    <div class="surveys-page">
      <div class="page-header">
        <div>
          <h1>{{ "SURVEY.assessmentManagement" | translate }}</h1>
          <p>{{ "SURVEY.assessmentManagementDesc" | translate }}</p>
        </div>
      </div>

      <!-- Filter rows -->
      <div class="filter-bar">
        <div class="filter-tabs">
          @for (tab of moduleTabs; track tab.key) {
            <button
              class="filter-tab"
              [class.active]="activeModuleFilter() === tab.key"
              (click)="activeModuleFilter.set(tab.key)"
            >
              <mat-icon>{{ tab.icon }}</mat-icon>
              {{ tab.labelKey | translate }}
              <span class="tab-count">{{ countByModule(tab.key) }}</span>
            </button>
          }
        </div>

        <mat-slide-toggle
          [checked]="showInactive()"
          (change)="onShowInactiveChange($event.checked)"
          color="primary"
        >
          {{ 'SURVEY.showInactive' | translate }}
        </mat-slide-toggle>
      </div>

      <div class="search-bar">
        <mat-icon>search</mat-icon>
        <input [ngModel]="searchQuery()" (ngModelChange)="searchQuery.set($event)"
               [placeholder]="'SURVEY.searchAssessments' | translate" class="search-input">
        @if (searchQuery()) {
          <button mat-icon-button (click)="searchQuery.set('')" class="search-clear">
            <mat-icon>close</mat-icon>
          </button>
        }
      </div>

      @if (loading()) {
        <div class="loading-center"><mat-spinner diameter="36" /></div>
      } @else if (filteredTemplates().length === 0) {
        <div class="empty-state">
          <mat-icon>assignment</mat-icon>
          <h3>{{ 'SURVEY.noTemplates' | translate }}</h3>
          <p>{{ 'SURVEY.createFirstTemplate' | translate }}</p>
          <button mat-raised-button color="primary" (click)="openCreateDialog()">
            <mat-icon>add</mat-icon> {{ 'SURVEY.newAssessment' | translate }}
          </button>
        </div>
      } @else {
        <div class="templates-grid">
          <div class="template-card create-card">
            <div class="create-plus"><mat-icon>add</mat-icon></div>
            <div class="create-title">{{ 'SURVEY.newTemplateCard' | translate }}</div>
            <div class="create-sub">{{ 'SURVEY.createBlankHint' | translate }}</div>
            <div class="create-options">
              <button mat-stroked-button class="create-opt" (click)="openCreateDialog()">
                <mat-icon>edit_note</mat-icon>
                {{ 'SURVEY.startFromScratch' | translate }}
              </button>
              <button mat-flat-button color="primary" class="create-opt ai" (click)="openAiGenerateDialog()">
                <mat-icon>auto_awesome</mat-icon>
                {{ 'SURVEY.aiGenerateShort' | translate }}
              </button>
            </div>
          </div>

          @for (t of filteredTemplates(); track t._id) {
            <div class="template-card"
                 [class.inactive]="!t.isActive"
                 [class.standardized]="!!t.instrumentId"
                 [class.highlighted]="t._id === highlightId()">

              <!-- Standardized instrument header bar -->
              @if (t.instrumentId) {
                <div class="instrument-bar">
                  <mat-icon>verified</mat-icon>
                  <span class="instrument-id">{{ t.instrumentId }}</span>
                  @if (t.instrumentVersion) {
                    <span class="instrument-version">v{{ t.instrumentVersion }}</span>
                  }
                  <span class="validated-label">{{ 'SURVEY.validatedInstrument' | translate }}</span>
                  @if (t.analysisPrompt) {
                    <span class="ai-prompt-badge" [matTooltip]="'SURVEY.hasCustomAIPrompt' | translate">
                      <mat-icon style="font-size:14px;width:14px;height:14px">auto_awesome</mat-icon>
                      {{ 'SURVEY.aiPrompt' | translate }}
                    </span>
                  }
                </div>
              }

              <div class="card-top">
                <div class="badges-row">
                  <div class="module-badge" [class]="t.moduleType">
                    <mat-icon>{{ moduleIcon(t.moduleType) }}</mat-icon>
                    {{ moduleLabel(t.moduleType) }}
                  </div>
                  <div class="intake-type-badge" [class]="t.intakeType">
                    <mat-icon>{{ intakeTypeIcon(t.intakeType) }}</mat-icon>
                    {{ intakeTypeLabel(t.intakeType) }}
                  </div>
                  @if (t.isAutoGenerated) {
                    <div class="ai-generated-badge"
                         [matTooltip]="'SURVEY.aiGeneratedTooltip' | translate">
                      <mat-icon>auto_awesome</mat-icon>
                      {{ 'SURVEY.aiGenerated' | translate }}
                    </div>
                  }
                </div>
                <div class="card-actions">
                  <mat-slide-toggle
                    [checked]="t.isActive"
                    (change)="toggleActive(t)"
                    [matTooltip]="t.isActive ? ('SURVEY.deactivate' | translate) : ('SURVEY.activate' | translate)"
                    color="primary"
                  ></mat-slide-toggle>
                  <button mat-icon-button [matMenuTriggerFor]="cardMenu">
                    <mat-icon>more_vert</mat-icon>
                  </button>
                  <mat-menu #cardMenu="matMenu">
                    <button mat-menu-item (click)="openEditDialog(t)">
                      <mat-icon>edit</mat-icon> {{ 'COMMON.edit' | translate }}
                    </button>
                    <button mat-menu-item (click)="copyTemplate(t)">
                      <mat-icon>content_copy</mat-icon> {{ 'SURVEY.copy' | translate }}
                    </button>
                    <button mat-menu-item (click)="copySurveyLink(t)">
                      <mat-icon>link</mat-icon> {{ 'SURVEY.copyLink' | translate }}
                    </button>
                    <button mat-menu-item (click)="viewResponses(t)">
                      <mat-icon>bar_chart</mat-icon> {{ 'SURVEY.viewResponses' | translate }}
                    </button>
                    <mat-divider></mat-divider>
                    <button mat-menu-item
                            (click)="clearResponses(t)"
                            [disabled]="(t.responseCount ?? 0) === 0">
                      <mat-icon>cleaning_services</mat-icon> {{ 'SURVEY.clearResponses' | translate }}
                    </button>
                    <button mat-menu-item class="danger-item" (click)="deleteTemplate(t)">
                      <mat-icon>delete</mat-icon> {{ 'COMMON.delete' | translate }}
                    </button>
                  </mat-menu>
                </div>
              </div>

              <h3>{{ t.title }}</h3>

              <div class="card-meta">
                <span class="meta-item">
                  <mat-icon>quiz</mat-icon>
                  {{ t.questions.length }} {{ 'SURVEY.questions' | translate }}
                </span>
                <span class="meta-item">
                  <mat-icon>people</mat-icon>
                  {{ t.responseCount ?? 0 }} {{ 'SURVEY.responses' | translate }}
                </span>
                <span class="meta-item">
                  <mat-icon>calendar_today</mat-icon>
                  {{ t.createdAt | date:'MMM d, y' }}
                </span>
              </div>

              <!-- Question preview -->
              <div class="questions-preview">
                @for (q of t.questions.slice(0, 3); track q.id) {
                  <div class="question-chip">
                    <mat-icon>{{ questionIcon(q.type) }}</mat-icon>
                    {{ q.text | slice:0:60 }}{{ q.text.length > 60 ? '…' : '' }}
                  </div>
                }
                @if (t.questions.length > 3) {
                  <div class="question-chip more">
                    +{{ t.questions.length - 3 }} {{ 'SURVEY.moreQuestions' | translate }}
                  </div>
                }
              </div>

              <div class="card-footer">
                <button mat-icon-button (click)="copySurveyLink(t)" [disabled]="!t.isActive"
                        [matTooltip]="'SURVEY.copyLink' | translate">
                  <mat-icon>link</mat-icon>
                </button>
                <button mat-icon-button (click)="assignIntake(t)" [disabled]="!t.isActive"
                        [matTooltip]="'SURVEY.assignAssessment' | translate">
                  <mat-icon>upload</mat-icon>
                </button>
                <button mat-icon-button (click)="previewTemplate(t)"
                        [disabled]="!t.questions.length"
                        [matTooltip]="'SURVEY.preview' | translate">
                  <mat-icon>visibility</mat-icon>
                </button>
                <button mat-icon-button (click)="openEditDialog(t)"
                        [matTooltip]="'COMMON.edit' | translate">
                  <mat-icon>edit</mat-icon>
                </button>
                <span class="footer-spacer"></span>
                <button mat-raised-button color="primary" (click)="viewResponses(t)"
                        [matTooltip]="(t.responseCount ?? 0) === 0 ? ('SURVEY.noResponsesYet' | translate) : ''">
                  <mat-icon>bar_chart</mat-icon>
                  {{ t.responseCount ?? 0 }}
                </button>
              </div>
            </div>
          }
        </div>
      }
    </div>
  `,
  styles: [`
    .surveys-page { padding: 32px; }

    .page-header {
      display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 24px;
      h1 { font-size: 28px; color: var(--artes-primary); margin: 0 0 4px; }
      p  { color: #5a6a7e; margin: 0; }
    }

    .filter-bar {
      display: flex; align-items: center; justify-content: space-between;
      margin-bottom: 12px; flex-wrap: wrap; gap: 8px;
    }

    .filter-tabs { display: flex; gap: 8px; flex-wrap: wrap; }
    .intake-type-tabs { margin-bottom: 24px; }

    .filter-tab {
      display: flex; align-items: center; gap: 6px;
      padding: 8px 16px; border-radius: 999px;
      border: 1px solid #dce6f0; background: white;
      font-size: 13px; cursor: pointer; color: #5a6a7e;
      transition: all 0.15s;
      mat-icon { font-size: 16px; width: 16px; height: 16px; }
      .tab-count {
        background: #f0f4f8; color: #5a6a7e;
        padding: 1px 7px; border-radius: 999px; font-size: 11px;
      }
      &.active {
        background: var(--artes-primary); color: white; border-color: var(--artes-primary);
        .tab-count { background: rgba(255,255,255,0.2); color: white; }
      }
      &:hover:not(.active) { border-color: var(--artes-accent); color: var(--artes-accent); }
    }

    .search-bar {
      display: flex; align-items: center; gap: 8px;
      background: white; border: 1px solid #dce6f0; border-radius: 999px;
      padding: 6px 16px; margin-bottom: 16px; max-width: 400px;
      mat-icon { color: #9aa5b4; font-size: 20px; width: 20px; height: 20px; }
      .search-input {
        border: none; outline: none; flex: 1; font-size: 13px;
        background: transparent; color: var(--artes-primary);
        &::placeholder { color: #9aa5b4; }
      }
      .search-clear { width: 24px; height: 24px; mat-icon { font-size: 16px; width: 16px; height: 16px; } }
    }

    .template-card.highlighted {
      border-color: var(--artes-accent, #3A9FD6);
      box-shadow: 0 0 0 2px rgba(58,159,214,0.25), 0 4px 20px rgba(58,159,214,0.15);
      animation: pulse-highlight 2s ease-out;
    }
    @keyframes pulse-highlight {
      0% { box-shadow: 0 0 0 4px rgba(58,159,214,0.4); }
      100% { box-shadow: 0 0 0 2px rgba(58,159,214,0.25), 0 4px 20px rgba(58,159,214,0.15); }
    }

    .loading-center { display: flex; justify-content: center; padding: 64px; }

    .empty-state {
      text-align: center; padding: 64px; background: white;
      border-radius: 16px; box-shadow: 0 2px 12px rgba(0,0,0,0.06);
      mat-icon { font-size: 56px; width: 56px; height: 56px; color: #9aa5b4; margin-bottom: 16px; }
      h3 { font-size: 20px; color: var(--artes-primary); margin-bottom: 8px; }
      p  { color: #5a6a7e; margin-bottom: 24px; }
    }

    .templates-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(360px, 1fr));
      gap: 20px;
    }

    /* Base card */
    .template-card {
      background: white; border-radius: 16px; padding: 20px 24px;
      box-shadow: 0 2px 12px rgba(0,0,0,0.06);
      display: flex; flex-direction: column; gap: 12px;
      transition: box-shadow 0.15s; border: 1.5px solid transparent;
      &:hover { box-shadow: 0 4px 20px rgba(0,0,0,0.10); }
      &.inactive { opacity: 0.65; }
    }

    /* "+ Create new" empty card slotted at the start of the grid.
       Offers two paths: start from scratch (manual editor) or AI generate. */
    .template-card.create-card {
      display: flex; flex-direction: column; align-items: center; justify-content: center;
      gap: 10px; padding: 28px 20px; min-height: 180px;
      background: #fbfdff; border: 2px dashed #c7d6e8; box-shadow: none;
      text-align: center;
      transition: background 0.18s, border-color 0.18s;
      &:hover { background: #f4f9ff; border-color: var(--artes-accent); }

      .create-plus {
        width: 52px; height: 52px; border-radius: 50%;
        display: flex; align-items: center; justify-content: center;
        background: linear-gradient(135deg, rgba(58,159,214,0.12), rgba(39,196,160,0.12));
        mat-icon { font-size: 28px; width: 28px; height: 28px; color: var(--artes-accent); }
      }
      .create-title {
        font-size: 15px; font-weight: 700; color: var(--artes-primary);
      }
      .create-sub {
        font-size: 12px; color: #7f8ea3; max-width: 260px; line-height: 1.5; margin-bottom: 4px;
      }
      .create-options {
        display: flex; flex-direction: column; gap: 8px; width: 100%; max-width: 260px;
      }
      .create-opt {
        width: 100%; justify-content: center; font-size: 13px; height: 36px;
        mat-icon { font-size: 18px; width: 18px; height: 18px; margin-right: 4px; }
      }
      .create-opt.ai {
        background: linear-gradient(135deg, #3A9FD6 0%, #27C4A0 100%) !important;
        color: white !important;
        mat-icon { color: white; }
      }
    }

    /* AI-generated marker on cards (auto-gen post-session, AI Generate Template,
       conflict recommended-action intakes). */
    .ai-generated-badge {
      display: inline-flex; align-items: center; gap: 4px;
      padding: 3px 10px; border-radius: 999px;
      font-size: 11px; font-weight: 700; text-transform: uppercase;
      letter-spacing: 0.4px;
      background: linear-gradient(135deg, rgba(124,58,237,0.10), rgba(58,159,214,0.10));
      color: #6b3aa0; border: 1px solid rgba(124,58,237,0.22);
      mat-icon { font-size: 13px; width: 13px; height: 13px; color: #7c3aed; }
    }

    /* Standardized instrument card — distinct blue-tinted style */
    .template-card.standardized {
      background: linear-gradient(160deg, #eef6fd 0%, #f8fbff 60%, white 100%);
      border-color: rgba(58,159,214,0.35);
      box-shadow: 0 2px 12px rgba(58,159,214,0.10);
      &:hover { box-shadow: 0 4px 20px rgba(58,159,214,0.18); }
    }

    /* Instrument identity bar (standardized only) */
    .instrument-bar {
      display: flex; align-items: center; gap: 6px;
      background: rgba(58,159,214,0.10); border-radius: 8px;
      padding: 5px 10px; margin: -4px -4px 0;
      mat-icon { font-size: 15px; width: 15px; height: 15px; color: #2080b0; }
      .instrument-id {
        font-size: 12px; font-weight: 800; color: var(--artes-primary); letter-spacing: 0.4px;
      }
      .instrument-version {
        font-size: 11px; color: #5a6a7e; background: rgba(0,0,0,0.07);
        padding: 1px 6px; border-radius: 4px;
      }
      .validated-label {
        margin-left: auto; font-size: 10px; font-weight: 700; text-transform: uppercase;
        letter-spacing: 0.5px; color: #2080b0;
      }
      .ai-prompt-badge {
        display: inline-flex; align-items: center; gap: 3px;
        font-size: 10px; font-weight: 700; text-transform: uppercase;
        letter-spacing: 0.4px; color: #7c3aed;
        background: rgba(124,58,237,0.08); padding: 1px 6px; border-radius: 4px;
      }
    }

    .card-top {
      display: flex; align-items: center; justify-content: space-between;
    }

    .badges-row { display: flex; align-items: center; gap: 6px; flex-wrap: wrap; }

    .module-badge, .intake-type-badge {
      display: inline-flex; align-items: center; gap: 5px;
      padding: 3px 10px; border-radius: 999px;
      font-size: 11px; font-weight: 700; text-transform: uppercase;
      mat-icon { font-size: 14px; width: 14px; height: 14px; }
    }
    .module-badge {
      &.conflict       { background: rgba(232,108,58,0.12); color: #c04a14; }
      &.neuroinclusion { background: rgba(39,196,160,0.12);  color: #1a9678; }
      &.succession     { background: rgba(58,159,214,0.12);  color: #2080b0; }
      &.coaching       { background: rgba(124,92,191,0.12);  color: #5e3fa8; }
    }
    .intake-type-badge {
      &.survey     { background: rgba(124,92,191,0.12); color: #6135b3; }
      &.interview  { background: rgba(27,42,71,0.10);   color: var(--artes-primary); }
      &.assessment { background: rgba(240,165,0,0.12);  color: #a06800; }
    }

    .card-actions { display: flex; align-items: center; gap: 4px; }

    h3 { font-size: 16px; color: var(--artes-primary); margin: 0; font-weight: 600; line-height: 1.3; }

    .card-meta {
      display: flex; gap: 16px; flex-wrap: wrap;
      .meta-item {
        display: flex; align-items: center; gap: 4px;
        font-size: 12px; color: #9aa5b4;
        mat-icon { font-size: 14px; width: 14px; height: 14px; }
      }
    }

    .questions-preview {
      display: flex; flex-direction: column; gap: 6px;
      .question-chip {
        display: flex; align-items: center; gap: 6px;
        background: #f8fafc; border-radius: 6px;
        padding: 6px 10px; font-size: 12px; color: #5a6a7e;
        mat-icon { font-size: 14px; width: 14px; height: 14px; color: #9aa5b4; flex-shrink: 0; }
        &.more { color: #9aa5b4; font-style: italic; }
      }
    }

    .card-footer {
      display: flex; gap: 4px; align-items: center; margin-top: 4px;
      .footer-spacer { flex: 1; }
    }

    .danger-item { color: #e53e3e; }
  `],
})
export class SurveyManagementComponent implements OnInit {
  private route = inject(ActivatedRoute);

  templates = signal<SurveyTemplate[]>([]);
  loading = signal(true);
  activeModuleFilter = signal('all');
  activeTypeFilter   = signal('all');
  showInactive       = signal(false);
  searchQuery        = signal('');
  highlightId        = signal<string | null>(null);

  moduleTabs = [
    { key: 'all',            labelKey: 'SURVEY.allModules',       icon: 'apps' },
    { key: 'conflict',       labelKey: 'SURVEY.moduleConflict',       icon: 'warning_amber' },
    { key: 'neuroinclusion', labelKey: 'SURVEY.moduleNeuroInclusion', icon: 'psychology' },
    { key: 'succession',     labelKey: 'SURVEY.moduleSuccession',     icon: 'trending_up' },
    { key: 'coaching',       labelKey: 'SURVEY.moduleCoaching',       icon: 'self_improvement' },
  ];

  filteredTemplates = computed(() => {
    let list = this.templates();
    if (this.activeModuleFilter() !== 'all') {
      list = list.filter((t) => t.moduleType === this.activeModuleFilter());
    }
    const typeFilter = this.activeTypeFilter();
    if (typeFilter === 'ai_generated') {
      list = list.filter((t) => t.isAutoGenerated);
    } else if (typeFilter !== 'all') {
      list = list.filter((t) => (t.intakeType ?? 'survey') === typeFilter && !t.isAutoGenerated);
    }
    const q = this.searchQuery().toLowerCase();
    if (q) {
      list = list.filter((t) =>
        t.title.toLowerCase().includes(q) ||
        (t.description ?? '').toLowerCase().includes(q) ||
        t.moduleType.toLowerCase().includes(q)
      );
    }
    // Highlighted template floats to top
    const hId = this.highlightId();
    return [...list].sort((a, b) => {
      if (hId) {
        if (a._id === hId) return -1;
        if (b._id === hId) return 1;
      }
      const aStd = a.instrumentId ? 1 : 0;
      const bStd = b.instrumentId ? 1 : 0;
      return bStd - aStd;
    });
  });

  countByModule = (key: string) =>
    key === 'all'
      ? this.templates().length
      : this.templates().filter((t) => t.moduleType === key).length;

  moduleIcon = (type: string) =>
    type === 'conflict' ? 'warning_amber'
    : type === 'neuroinclusion' ? 'psychology'
    : type === 'coaching' ? 'self_improvement'
    : 'trending_up';

  moduleLabel = (type: string) => {
    const map: Record<string, string> = { conflict: 'SURVEY.moduleConflict', neuroinclusion: 'SURVEY.moduleNeuroInclusion', coaching: 'SURVEY.moduleCoaching', succession: 'SURVEY.moduleSuccession' };
    return this.translateSvc.instant(map[type] ?? type);
  };

  intakeTypeIcon = (type: string) =>
    type === 'interview' ? 'record_voice_over' : type === 'assessment' ? 'fact_check' : 'poll';

  intakeTypeLabel = (type: string) => {
    const map: Record<string, string> = { interview: 'SURVEY.typeInterview', assessment: 'SURVEY.typeAssessment', survey: 'SURVEY.typeSurvey' };
    return this.translateSvc.instant(map[type] ?? type);
  };

  questionIcon = (type: string) =>
    type === 'scale' ? 'linear_scale' : type === 'boolean' ? 'toggle_on'
    : type === 'forced_choice' ? 'compare_arrows' : 'short_text';

  constructor(
    private api: ApiService,
    private dialog: MatDialog,
    private snackBar: MatSnackBar,
    private translateSvc: TranslateService,
  ) {}

  ngOnInit(): void {
    const highlight = this.route.snapshot.queryParamMap.get('highlight');
    if (highlight) {
      this.highlightId.set(highlight);
      this.activeTypeFilter.set('ai_generated');
    }
    // Each /intakes/<type> route carries its filter via route data; subscribe so
    // that switching from Surveys → Interviews via the nav updates the filter.
    this.route.data.subscribe((data) => {
      const f = (data['typeFilter'] as string | undefined) ?? 'all';
      this.activeTypeFilter.set(f);
    });
    this.loadTemplates();
  }

  loadTemplates(): void {
    this.loading.set(true);
    const params: string[] = [];
    if (this.showInactive()) params.push('includeInactive=true');
    params.push('includeAutoGenerated=true');
    const url = params.length ? `/surveys/templates?${params.join('&')}` : '/surveys/templates';
    this.api.get<SurveyTemplate[]>(url).subscribe({
      next: (templates) => {
        this.templates.set(templates);
        this.loading.set(false);
        templates.forEach((t) => this.loadResponseCount(t._id));
      },
      error: () => this.loading.set(false),
    });
  }

  onShowInactiveChange(value: boolean): void {
    this.showInactive.set(value);
    this.loadTemplates();
  }


  loadResponseCount(templateId: string): void {
    this.api.get<{ count: number }>(`/surveys/responses/${templateId}/count`).subscribe({
      next: (data) => {
        this.templates.update((list) =>
          list.map((t) => (t._id === templateId ? { ...t, responseCount: data.count } : t))
        );
      },
      error: () => {},
    });
  }

  openCreateDialog(): void {
    const ref = this.dialog.open(SurveyTemplateDialogComponent, {
      minWidth: '960px',
      maxWidth: '1100px',
      maxHeight: '92vh',
      disableClose: true,
    });
    ref.afterClosed().subscribe((result) => { if (result) this.loadTemplates(); });
  }

  openAiGenerateDialog(): void {
    import('../ai-generate-template-dialog/ai-generate-template-dialog.component').then((m) => {
      const ref = this.dialog.open(m.AiGenerateTemplateDialogComponent, {
        width: '640px', maxWidth: '92vw', maxHeight: '92vh',
      });
      ref.afterClosed().subscribe((result) => { if (result) this.loadTemplates(); });
    });
  }

  /** Open the same walkthrough preview the editor uses, hydrated from a saved
   *  template — non-saving, just a respondent-eye view. If a sibling translation
   *  matching the user's UI language exists, preview that instead of the source. */
  previewTemplate(t: SurveyTemplate): void {
    if (!t.questions?.length) return;
    const uiLang = this.translateSvc.currentLang || 'en';
    if (t.language === uiLang) { this.openPreviewDialog(t); return; }

    this.api.get<{ _id: string; title: string; language: string }[]>(
      `/surveys/templates/${t._id}/translations`,
    ).subscribe({
      next: (siblings) => {
        const match = siblings?.find((s) => s.language === uiLang);
        if (!match) { this.openPreviewDialog(t); return; }
        this.api.get<SurveyTemplate>(`/surveys/templates/${match._id}`).subscribe({
          next: (full) => this.openPreviewDialog(full),
          error: () => this.openPreviewDialog(t),
        });
      },
      error: () => this.openPreviewDialog(t),
    });
  }

  private openPreviewDialog(t: SurveyTemplate): void {
    import('../survey-preview-dialog/survey-preview-dialog.component').then((m) => {
      this.dialog.open(m.SurveyPreviewDialogComponent, {
        width: '780px', maxWidth: '94vw', maxHeight: '92vh',
        data: {
          title: t.title,
          description: t.description,
          instructions: t.instructions,
          questions: t.questions.map((q) => ({
            id: q.id,
            text: q.text,
            type: q.type,
            category: q.category,
            options: (q as { options?: { value: string; text: string }[] }).options,
            scale_range: (q as { scale_range?: { min: number; max: number; labels?: Record<string, string> } }).scale_range,
          })),
        },
      });
    });
  }

  openEditDialog(template: SurveyTemplate): void {
    const ref = this.dialog.open(SurveyTemplateDialogComponent, {
      minWidth: '960px',
      maxWidth: '1100px',
      maxHeight: '92vh',
      disableClose: true,
      data: template,
    });
    ref.afterClosed().subscribe((result) => {
      if (result?.openTemplate) {
        this.loadTemplates();
        setTimeout(() => this.openEditDialog(result.openTemplate), 200);
      } else if (result) {
        this.loadTemplates();
      }
    });
  }

  toggleActive(template: SurveyTemplate): void {
    const newValue = !template.isActive;
    this.templates.update((list) =>
      list.map((t) => (t._id === template._id ? { ...t, isActive: newValue } : t))
    );
    this.api.put(`/surveys/templates/${template._id}`, { isActive: newValue }).subscribe({
      next: () => {
        this.snackBar.open(
          this.translateSvc.instant(newValue ? 'SURVEY.templateActivated' : 'SURVEY.templateDeactivated'),
          this.translateSvc.instant('COMMON.close'),
          { duration: 2500 }
        );
      },
      error: () => {
        this.templates.update((list) =>
          list.map((t) => (t._id === template._id ? { ...t, isActive: template.isActive } : t))
        );
        this.snackBar.open(this.translateSvc.instant('SURVEY.updateStatusFailed'), this.translateSvc.instant('COMMON.close'), { duration: 3000 });
      },
    });
  }

  copyTemplate(template: SurveyTemplate): void {
    // Strip runtime/server fields, keep all schema fields
    const { _id, createdAt, responseCount, isGlobal, ...rest } = template as any;
    this.api.post<SurveyTemplate>('/surveys/templates', {
      ...rest,
      title: `${template.title} (Copy)`,
      isActive: false,
      isGlobal: false,
    }).subscribe({
      next: () => {
        this.snackBar.open(this.translateSvc.instant('SURVEY.templateCopied'), this.translateSvc.instant('COMMON.close'), { duration: 3500 });
        this.loadTemplates();
      },
      error: () => this.snackBar.open(this.translateSvc.instant('SURVEY.copyFailed'), this.translateSvc.instant('COMMON.close'), { duration: 2500 }),
    });
  }

  clearResponses(template: SurveyTemplate): void {
    const count = template.responseCount ?? 0;
    const ref = this.dialog.open(ConfirmDialogComponent, {
      width: '440px',
      data: {
        title: this.translateSvc.instant('SURVEY.clearAllResponses'),
        message: this.translateSvc.instant('SURVEY.clearResponsesConfirm', { count, title: template.title }),
        confirmLabel: this.translateSvc.instant('SURVEY.clearResponses'),
      },
    });
    ref.afterClosed().subscribe((confirmed) => {
      if (!confirmed) return;
      this.api.delete<{ deletedCount: number }>(`/surveys/responses/${template._id}`).subscribe({
        next: (res) => {
          this.templates.update((list) =>
            list.map((t) => (t._id === template._id ? { ...t, responseCount: 0 } : t))
          );
          this.snackBar.open(this.translateSvc.instant('SURVEY.responsesCleared', { count: res.deletedCount ?? count }), this.translateSvc.instant('COMMON.close'), { duration: 2500 });
        },
        error: () => this.snackBar.open(this.translateSvc.instant('SURVEY.clearResponsesFailed'), this.translateSvc.instant('COMMON.close'), { duration: 2500 }),
      });
    });
  }

  assignIntake(template: SurveyTemplate): void {
    this.dialog.open(IntakeAssignDialogComponent, {
      width: '580px',
      maxHeight: '90vh',
      data: { _id: template._id, title: template.title },
    });
  }

  copySurveyLink(template: SurveyTemplate): void {
    const url = `${window.location.origin}/intake/${template._id}`;
    navigator.clipboard.writeText(url).then(() => {
      this.snackBar.open(this.translateSvc.instant('SURVEY.linkCopied'), this.translateSvc.instant('COMMON.close'), { duration: 2500 });
    });
  }

  viewResponses(template: SurveyTemplate): void {
    this.dialog.open(SurveyResponsesDialogComponent, {
      width: '760px',
      maxHeight: '90vh',
      data: template,
    });
  }

  deleteTemplate(template: SurveyTemplate): void {
    const ref = this.dialog.open(ConfirmDialogComponent, {
      width: '420px',
      data: {
        title: this.translateSvc.instant('SURVEY.deleteTemplate'),
        message: this.translateSvc.instant('SURVEY.deleteTemplateConfirm', { title: template.title }),
        confirmLabel: this.translateSvc.instant('COMMON.delete'),
      },
    });
    ref.afterClosed().subscribe((confirmed) => {
      if (!confirmed) return;
      this.api.delete(`/surveys/templates/${template._id}`).subscribe({
        next: () => {
          this.templates.update((list) => list.filter((t) => t._id !== template._id));
          this.snackBar.open(this.translateSvc.instant('SURVEY.templateDeleted'), this.translateSvc.instant('COMMON.close'), { duration: 2500 });
        },
        error: () => this.snackBar.open(this.translateSvc.instant('SURVEY.deleteFailed'), this.translateSvc.instant('COMMON.close'), { duration: 2500 }),
      });
    });
  }
}
