import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-terms-of-service',
  standalone: true,
  imports: [CommonModule, RouterLink, MatIconModule, MatButtonModule],
  template: `
    <div class="legal-page">
      <header class="legal-header">
        <a routerLink="/" class="logo-link">
          <img src="assets/artes-logo-full-white.png" alt="ARTES" class="logo" onerror="this.style.display='none'" />
          <span class="logo-text">ARTES</span>
        </a>
        <nav>
          <a routerLink="/privacystatement" class="nav-link">Privacy Statement</a>
          <a routerLink="/login" mat-stroked-button class="nav-btn">Sign in</a>
        </nav>
      </header>

      <main class="legal-content">
        <div class="hero">
          <mat-icon class="hero-icon">gavel</mat-icon>
          <h1>Terms of Service</h1>
          <p class="subtitle">Last updated: 17 April 2026</p>
        </div>

        <article class="document">

          <section>
            <h2>1. Introduction</h2>
            <p>These Terms of Service ("Terms") govern your access to and use of the ARTES platform ("Platform", "Service"), operated by HeadSoft Technology in partnership with Helena Coaching ("we", "us", "our"). By accessing or using the Platform, you agree to be bound by these Terms.</p>
            <p>ARTES is a multi-tenant B2B SaaS platform designed for organisational development, coaching, and people intelligence. The Platform is available at <strong>artes.helenacoaching.com</strong>.</p>
          </section>

          <section>
            <h2>2. Definitions</h2>
            <ul>
              <li><strong>"Organisation"</strong> means the entity that has subscribed to the Platform and manages its own users, departments, and data.</li>
              <li><strong>"User"</strong> means any individual granted access to the Platform by their Organisation, including administrators, HR managers, managers, coaches, and coachees.</li>
              <li><strong>"Content"</strong> means any data, text, responses, analyses, or materials submitted to or generated by the Platform.</li>
              <li><strong>"AI Features"</strong> means any functionality powered by artificial intelligence, including conflict analysis, neuroinclusion gap assessments, individual development plan generation, and coaching insights.</li>
            </ul>
          </section>

          <section>
            <h2>3. Account Registration and Access</h2>
            <p>3.1. Access to the Platform is provided on an Organisation basis. Your Organisation's administrator is responsible for managing user accounts and role assignments.</p>
            <p>3.2. You must provide accurate and complete information when your account is created. You are responsible for maintaining the confidentiality of your login credentials.</p>
            <p>3.3. The Platform supports the following roles with varying access levels: System Administrator, Organisation Administrator, HR Manager, Manager, Coach, and Coachee. Your access is governed by the role assigned to you.</p>
            <p>3.4. You must not share your credentials, attempt to access accounts belonging to others, or circumvent access controls.</p>
          </section>

          <section>
            <h2>4. Acceptable Use</h2>
            <p>You agree to use the Platform only for its intended purpose — organisational development, coaching, people analytics, and related professional activities. You must not:</p>
            <ul>
              <li>Use the Platform for any unlawful purpose or in violation of any applicable laws or regulations.</li>
              <li>Attempt to reverse-engineer, decompile, or extract source code from the Platform.</li>
              <li>Interfere with the Platform's operation, security, or other users' access.</li>
              <li>Submit false, misleading, or malicious content including in survey responses or coaching intake forms.</li>
              <li>Use AI-generated analyses as the sole basis for employment decisions without human review.</li>
              <li>Scrape, harvest, or collect data from the Platform by automated means.</li>
            </ul>
          </section>

          <section>
            <h2>5. Subscription and Billing</h2>
            <p>5.1. The Platform is offered through tiered subscription plans. Your Organisation's plan determines the features available and the maximum number of users.</p>
            <p>5.2. Subscription fees are billed at the Organisation level. Payment processing is handled securely through Stripe. We do not store credit card details on our servers.</p>
            <p>5.3. Subscriptions renew automatically unless cancelled before the renewal date. Your Organisation administrator can manage the subscription from the billing section of the Platform.</p>
            <p>5.4. We reserve the right to modify pricing with 30 days' written notice. Existing subscriptions will be honoured until the next renewal cycle.</p>
          </section>

          <section>
            <h2>6. Data Ownership and Intellectual Property</h2>
            <p>6.1. <strong>Your Data:</strong> Your Organisation retains full ownership of all data submitted to the Platform, including survey responses, coaching notes, assessment results, and organisational information. We claim no ownership over your data.</p>
            <p>6.2. <strong>AI-Generated Content:</strong> Analyses, narratives, scripts, and development plans generated by the Platform's AI features are provided to your Organisation for its use. These outputs are derived from your data and standard organisational development methodologies.</p>
            <p>6.3. <strong>Platform IP:</strong> The Platform software, design, algorithms, and underlying technology remain the intellectual property of HeadSoft Technology. Your subscription grants a non-exclusive, non-transferable licence to use the Platform for the subscription term.</p>
            <p>6.4. <strong>Feedback:</strong> If you provide feedback or suggestions about the Platform, we may use them to improve the service without obligation to you.</p>
          </section>

          <section>
            <h2>7. AI Features and Limitations</h2>
            <p>7.1. The Platform uses AI (powered by Anthropic's Claude) to generate conflict analyses, neuroinclusion assessments, individual development plans, and coaching insights.</p>
            <p>7.2. AI-generated content is intended as a professional support tool, not a replacement for qualified human judgment. All AI outputs should be reviewed by appropriate professionals before action is taken.</p>
            <p>7.3. We do not guarantee the accuracy, completeness, or suitability of AI-generated content for any particular purpose. AI analyses are based on the data provided and standard organisational psychology frameworks.</p>
            <p>7.4. Your data is processed by the AI model for the sole purpose of generating the requested analysis. We do not use your data to train AI models.</p>
          </section>

          <section>
            <h2>8. Privacy and Data Protection</h2>
            <p>8.1. Your privacy is important to us. Our collection and processing of personal data is governed by our <a routerLink="/privacystatement">Privacy Statement</a>.</p>
            <p>8.2. The Platform is designed with privacy-by-design principles, including data segregation between organisations, minimum group sizes for survey aggregation (5 respondents), and anonymous survey options.</p>
            <p>8.3. We act as a Data Processor on behalf of your Organisation (the Data Controller) for the purposes of GDPR and equivalent data protection legislation.</p>
          </section>

          <section>
            <h2>9. Third-Party Integrations</h2>
            <p>9.1. The Platform integrates with third-party services including Google Calendar, Microsoft 365 (Outlook), Google Meet, Microsoft Teams, and Stripe. Your use of these integrations is subject to the respective third-party terms of service.</p>
            <p>9.2. Calendar integrations require explicit OAuth consent. Tokens are stored encrypted and can be revoked at any time from the Platform settings.</p>
            <p>9.3. We are not responsible for the availability, accuracy, or security of third-party services.</p>
          </section>

          <section>
            <h2>10. Service Availability</h2>
            <p>10.1. We strive to maintain high availability of the Platform but do not guarantee uninterrupted access. The Platform may be temporarily unavailable for maintenance, updates, or due to circumstances beyond our control.</p>
            <p>10.2. We will make reasonable efforts to provide advance notice of planned maintenance that may affect availability.</p>
          </section>

          <section>
            <h2>11. Limitation of Liability</h2>
            <p>11.1. To the maximum extent permitted by law, HeadSoft Technology and Helena Coaching shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Platform.</p>
            <p>11.2. Our total liability for any claims arising from the use of the Platform shall not exceed the total subscription fees paid by your Organisation in the 12 months preceding the claim.</p>
            <p>11.3. We do not accept liability for decisions made based on AI-generated content. The Platform is a decision-support tool, not a decision-making authority.</p>
          </section>

          <section>
            <h2>12. Termination</h2>
            <p>12.1. Your Organisation may terminate its subscription at any time. Upon termination, access to the Platform will cease at the end of the current billing period.</p>
            <p>12.2. We may suspend or terminate access if you breach these Terms, fail to pay subscription fees, or engage in activity that threatens the Platform's security or other users.</p>
            <p>12.3. Upon termination, your Organisation may request an export of its data within 30 days. After this period, data will be permanently deleted in accordance with our data retention policy.</p>
          </section>

          <section>
            <h2>13. Changes to Terms</h2>
            <p>We may update these Terms from time to time. We will notify Organisation administrators of material changes at least 30 days before they take effect. Continued use of the Platform after changes take effect constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2>14. Governing Law</h2>
            <p>These Terms are governed by the laws of the Czech Republic. Any disputes arising under these Terms shall be resolved in the competent courts of Prague, Czech Republic.</p>
          </section>

          <section>
            <h2>15. Contact</h2>
            <p>For questions about these Terms, please contact:</p>
            <div class="contact-card">
              <p><strong>HeadSoft Technology</strong></p>
              <p>Email: <a href="mailto:legal@helenacoaching.com">legal&#64;helenacoaching.com</a></p>
              <p>Platform: <a href="https://artes.helenacoaching.com">artes.helenacoaching.com</a></p>
            </div>
          </section>

        </article>
      </main>

      <footer class="legal-footer">
        <div class="footer-inner">
          <span>&copy; 2026 HeadSoft Technology &times; Helena Coaching. All rights reserved.</span>
          <div class="footer-links">
            <a routerLink="/termsofservice">Terms of Service</a>
            <a routerLink="/privacystatement">Privacy Statement</a>
          </div>
        </div>
      </footer>
    </div>
  `,
  styles: [`
    :host { display: block; min-height: 100vh; background: #f8fafb; }

    .legal-page { display: flex; flex-direction: column; min-height: 100vh; }

    .legal-header {
      display: flex; align-items: center; justify-content: space-between;
      padding: 16px 40px; background: #1B2A47;
    }
    .logo-link {
      display: flex; align-items: center; gap: 10px;
      text-decoration: none; color: #fff;
    }
    .logo { height: 32px; }
    .logo-text { font-size: 20px; font-weight: 700; letter-spacing: 2px; color: #fff; }
    .legal-header nav { display: flex; align-items: center; gap: 16px; }
    .nav-link { color: rgba(255,255,255,0.8); text-decoration: none; font-size: 14px; &:hover { color: #fff; } }
    .nav-btn { color: #fff !important; border-color: rgba(255,255,255,0.4) !important; font-size: 14px !important; }

    .legal-content { flex: 1; max-width: 800px; width: 100%; margin: 0 auto; padding: 0 24px 60px; }

    .hero {
      text-align: center; padding: 48px 0 32px;
    }
    .hero-icon { font-size: 48px; width: 48px; height: 48px; color: #3A9FD6; margin-bottom: 12px; }
    .hero h1 { font-size: 36px; color: #1B2A47; margin: 0 0 8px; font-weight: 700; }
    .subtitle { color: #6b7c93; font-size: 14px; margin: 0; }

    .document { background: #fff; border-radius: 16px; padding: 48px; box-shadow: 0 2px 16px rgba(0,0,0,0.04); }

    section { margin-bottom: 32px; &:last-child { margin-bottom: 0; } }

    h2 {
      font-size: 18px; color: #1B2A47; font-weight: 600; margin: 0 0 12px;
      padding-bottom: 8px; border-bottom: 1px solid #eef2f6;
    }

    p { font-size: 15px; line-height: 1.7; color: #3d4f63; margin: 0 0 10px; }

    ul { padding-left: 20px; margin: 8px 0 12px; }
    li { font-size: 15px; line-height: 1.7; color: #3d4f63; margin-bottom: 6px; }

    a { color: #3A9FD6; text-decoration: none; &:hover { text-decoration: underline; } }

    .contact-card {
      background: #f4f7fa; border-radius: 10px; padding: 16px 20px; margin-top: 12px;
      p { margin: 0 0 4px; &:last-child { margin: 0; } }
    }

    .legal-footer {
      background: #1B2A47; color: rgba(255,255,255,0.7); padding: 20px 40px;
    }
    .footer-inner {
      max-width: 800px; margin: 0 auto;
      display: flex; justify-content: space-between; align-items: center;
      font-size: 13px;
    }
    .footer-links { display: flex; gap: 20px; }
    .footer-links a { color: rgba(255,255,255,0.7); text-decoration: none; &:hover { color: #fff; } }

    @media (max-width: 640px) {
      .legal-header { padding: 12px 16px; }
      .legal-content { padding: 0 12px 40px; }
      .document { padding: 24px 20px; }
      .hero h1 { font-size: 28px; }
      .footer-inner { flex-direction: column; gap: 8px; text-align: center; }
    }
  `],
})
export class TermsOfServiceComponent {}
